# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='birthday_str',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения, строкой'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='coaches',
            field=models.ManyToManyField(blank=True, to='sports_schools.Coach', verbose_name='Тренера'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='food_regime',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_books.FoodRegime', verbose_name='Пищевой режим'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='housing',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference_books.Housing', verbose_name='Жилищные условия'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='sport',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='patients', to='reference_books.Sport', verbose_name='Вид спорта'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='tournament_sports',
            field=models.ManyToManyField(blank=True, help_text='По каким видам спорта участвовал в соревнованиях', to='reference_books.Sport', verbose_name='Соревнования'),
        ),
    ]
