# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_auto_20171202_1010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='birthday_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Дата рождения, строкой'),
        ),
    ]
