# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-02 10:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_auto_20171202_1013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='training_from_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='С какого года тренируется'),
        ),
    ]
