# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-13 15:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_auto_20180113_1453'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='patient',
            options={'ordering': ['full_name'], 'verbose_name': 'Пациент', 'verbose_name_plural': 'Пациенты'},
        ),
        migrations.RemoveField(
            model_name='patient',
            name='alcohol',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='disease',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='education',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='food_regime',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='housing',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='injuries',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='operations',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='other_sports',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='polyclinic',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='profession',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='smoking',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='tournament_sports',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='work',
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday',
            field=models.DateField(null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='birthday_str',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name=''),
        ),
        migrations.AlterField(
            model_name='patient',
            name='emo_limit',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Допуск ЭМО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='training_from_year',
            field=models.CharField(blank=True, choices=[('2003', 2003), ('2004', 2004), ('2005', 2005), ('2006', 2006), ('2007', 2007), ('2008', 2008), ('2009', 2009), ('2010', 2010), ('2011', 2011), ('2012', 2012), ('2013', 2013), ('2014', 2014), ('2015', 2015), ('2016', 2016), ('2017', 2017)], max_length=20, null=True, verbose_name='С какого года тренируется'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='umo_limit',
            field=models.TextField(blank=True, max_length=255, null=True, verbose_name='Допуск УМО'),
        ),
    ]
