# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-25 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0007_patient_team_member'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='recommendations',
            field=models.TextField(blank=True, null=True, verbose_name='Рекомендации'),
        ),
    ]
