# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2021-06-03 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0008_patient_recommendations'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='emo_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер ЭМО'),
        ),
        migrations.AddField(
            model_name='patient',
            name='umo_number',
            field=models.PositiveIntegerField(default=0, verbose_name='Номер УМО'),
        ),
        migrations.AlterField(
            model_name='patient',
            name='training_from_year',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='С какого года тренируется'),
        ),
    ]
